---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: alertmanager-discord
  namespace: monitoring
spec:
  chart:
    spec:
      chart: alertmanager-discord
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: harbor
      version: '>=0.2.0'
  interval: 1h
  values:
    configAsSecret:
      name: discord-config
