---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: alertmanager-discord
  namespace: monitoring
spec:
  chart:
    spec:
      chart: alertmanager-discord
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: masgustavos
      version: 0.0.5
  interval: 1h
  values:
    # -- If you don't want to expose your webhooks, create the config as a secret with the key "config"
    configAsSecret:
      name: discord-config
