---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: alertmanager-discord
  namespace: monitoring
spec:
  install:
    remediation:
      retries: -1
  uninstall:
    timeout: 5m
    disableHooks: false 
    keepHistory: false
  upgrade:
    # Remediaton configuration for when an Helm upgrade action fails
    remediation:
      # Amount of retries to attempt after a failure,
      # setting this to 0 means no remedation will be
      # attempted
      retries: 5
  # Configuration options for the Helm rollback action
  rollback:
    timeout: 5m
    disableWait: false
    disableHooks: false
    recreate: false
    force: false
    cleanupOnFail: false
  chart:
    spec:
      chart: alertmanager-discord
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: harbor
      version: '>=0.2.0'
  interval: 1h
  values:
    configAsSecret:
      name: discord-config
    imagePullSecrets:
      name: helm-harbor
