apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: helm-harbor
  namespace: monitoring
spec:
  encryptedData:
    password: AgAMxExTCHpSU3dcgiMcOCQqqvFVldiH5eE1lB5Lj1rfFiJ4mgCtlSzyi1OD8fjYQKru7jUMx4V96ieGkPjKrsmtS+8a3KLwj4wSNuLyTDQA5LQnfC7h75ekZ9YlC7KI/9KfxbSbplP7+LOb2NDuNbos+uPwlD+6/S9XoINp4TDA8peLfbtXJfCdNHE9pYCgYUBP4F9f6xqj1Mj3wtb4CN2XywrHM4ZXf/OTyuc7FRXWf1f5174KJtSA3WURo/0/aKrANfteaLpxUfjIyYnTBGiqR7TkAcsfT1oZMct37ZX3alXjln+1Yo+mIsl9LfJPPNSpLXo+4ASFdgqikdP3/MQqTpIfZTbCUjxZ+Csyb/7cOl7Dt4mj75waYdlQvLGykYUssak6wIrmoMEKV1bN+yz5LL9KKvdMRaKXW5OtRsKdHRQlL7WXz3LzSKDjpYstVpOksZk1RULSGHiJPbPUZdGBYC2WDgi08EPg//J/2+nOOmK/FGnWAwIcgrKULakyNDEvOhlHg88BgYfJY7ftbq2wJo1Aj8ItOaVG8tvhxi0gE11CePYv+I5WzoUVAQj/FChpDfc+q8LS5WddMVXj00ko4/jnomI1FyuPj7Y415kBWTRYWLti3sggrQ3oSdr3h2lRmo/YnuhndKxKMDwTm05PeWF+Nr/XMcc2wEp/1fyqNXIXUaJlTKUuQJdCBHYfLUtrl8uzWmcwkw==
    username: AgB+CR1CfNBBYjPsUF4SB1I7A8ejpsewhiDYI801lKKaKk4nSL3Y0HvKHUvH1ysPdsfGTKvK3eQC3Q9xlX+tzfRfcES+dI9nCVGOga7KMmSfAxa4QoHQZRlK+1togEm7PsjrBPIHgL8p2mA1bfkGYgJPPEsghFgF9lnFYPhxlGVWKT0Fm2gy2/EEMPWW2kazua55NKURLKaJrI8NwXov8b77bFTee7pqxaGrwckPOS/J/coUM1qFPPYClz8JGaFQC4OkbDDlyh97xk8r1xeBGEPGbKVR9SnM41CHtZe0UQ3TIiWAqkUlGn6Bf/w/OSDMEwkswTS7VPVzh6IRDjoLUrNbP/SzCvtm7HEYil+5nfabjb+OL8D9xkexNOwqbniOA1cUCpG9knnbjjfUZw9Z2jycCI3vgyad2jbvdnwIdCRThFAn4bvk0gu1UcMEJ9v3XnmMaVQeEA1TSCaJG81bhEQwEVRd/Bw5WwHzlXenRAI44wXvL6+9Rl8gA9U+77UUqw6UEIUc9nmeyhr6UygFnddchTeyCBiHmJgKneNquFOn2sXB2HMXwsI88x8dfpPT0+0hyaIkhMjVlnUQuEunSG0YFODx3snk3rZ+N34vjrXLe7Z3LqqvQl5mPV7T1vt5LfTjHg3Wbvk4+cQ6dOYO0VFvxh+2P5LTS85wNF70SKuxWKvsaMvlrWDVTsUqRrxwKjDr0zVT6Q==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: helm-harbor
      namespace: monitoring

