apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: helm-harbor
  namespace: monitoring
spec:
  encryptedData:
    password: AgApDOC4+Ih4IxMgCSjgnuLJAJrabdCfFLcXIV9pGIC5QRxKWdIlktXf539kJpfO3Fk2qk7YHcrnb2QDX7jeATa2RnvgT+C791JtinY5E8POlt/AUhRrBNMEArd8zdfApnzzbqDZyOlXogbnafbpN1YNO5U5FUWsIYtG3oK6RQshrPTYP2w5+M+Guptv66Bhd9PQ5yIzFgodXN8qU5ykaCA+zN823nJya9fIfnkQ+FtXP1KUT3vvkMsdZRezSJ0lsVAfdg5M3kJ425SSbx0CH/UQVMA8ss4d1oU1uI9XN0Ces1RBQnYy4svFYtwA7xG7PsWo6fR2dw2p6iHrAJZutAw88c9g73JWL/uHeiKcfExJU1moyKftrIfsRs2XG8hpsvLaQ8aL3FU6BjpLKaQkaw8L3Dn3xFTPq3ZgeLqZsWAEnFl943aMKycT2Q4nKA70ysN7vXuRyiRVg6kWMurjWlD7e3q92ZlY3Sp3tL1QuwooMM6KdM9WJQF/ktxogrTovnwfL8gtG3f2CvKU1YIY0fL8j2bKDu8YdAZWi0n2+q2pqEWzNUWdEMYZ25nhZgNnH9qJUO9OxTdMMw9ujqjGH4BjZ5x9jlaK94oFODycFDbgrtFM5+3Y9GTaMCD40ABw3kkC5wj5eJ0GzFho79KfVvf4HgVRh0crmJYWvndct1LtWSAQEiF+GnFn/6GnFy3ZTfoeONAv5IepCw==
    username: AgA3nUUBfQN/4kRXJBdmDapWPVKLPnG46M7BOdxkXGBVDnDhUhg9dd0dWxNkTwGP0F/8/KrJO0QaP8IhFkEPzmg4iuSX4Vn2816OC1Jgti6VdgEqRlAYfjMJ3m3D51PMs0NOaxSYHwtsFNjYU1aNtM7VLJTdd1eWvBTVR2UAN+1SFP98/xCIlkRqZt2N4zgu0uRdd06H3FAnvfrQsbixWCVMZbsMI5wfSzP9pryxBnNcHV5uG870nyBXUVuv9oEK39ye23r287QegSan+FPTFWv+AiIX2veDnPkce1hNIX/67OZ4YDgvP7JvuqXmF5eoWjZEjJ4N+wGtk3MO1gjeEZG0CaXj+ojDDuWQxvTUyNgi+CRNdxTE9bRxYw7pmAbNmouAc4j0ss1i2zTg4i/4b9KsEn7HlRgBKpzhn/AyYmqp5iCX5THUXAn/mjlKAKYf/oCoMt4cqEiSURfXGDaVoDp5oWbj2VeL24ZVm8SFl1SgqE/WZju14WQezGha7ntHyB4jN23WSLbeTzscY2uLmTKvv0Ky3mxnG2lp715pla+TN/q8GaCAqgwuz343kkZ0wkzqCk/ETemhXkuOxGMkwrqTAxH4CcxmtNuvxikaBd/bP9HtkeYozc6jFwOaJoTlX7vbWXSjePf5vJMTsZfztFIfZhIba3L4gmrrgN/Bq6szlN4UPgGLQENvN2otyo4lA5PjQPtqpw==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: helm-harbor
      namespace: monitoring

