apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: helm-harbor
  namespace: monitoring
spec:
  encryptedData:
    password: AgArcyr+ir96NGOi9LKoBex1tm/BUjuZT+3uzLOq4ClXF+ZXJsaBQpKoOxUH4xBOBA3flU50gN3RUjU/51gXbj52iWDeGXuWvF+bx3WrKhaI3ouS9XbUuarN8E6ndDaYMythYERmuNk+Vi9FIAjHMrw0TXswDad9RVkWzp6gAnSmkCTDJCWrWfO1puczI++aLRFZ168c3VY7NeWtjTRWn27vlAMoS/nSchdXfrah/zYlqNkjT1w2FehrrKPFr3jp1fohnBLCecoGZ4D8NTb8Qsx0UndZFCLc0wchZu66hHwP4FZuWe+c8C4lC0vrapMIsG0FwvijGd26wQh0ZRKQRvhiZ0zwQFCdkgymj7eSHWYbxlg7wAJV9M8+TPn/E/XfX5rQ++gAlBPjC8mFeCpiQCG1kWnZTvB//kV3NuhrKQR2OcX4mlfjueDAUnx2I4HKH5F6oDfD6XbB49oCf8iRPLT2anR5yEtgdnnhJZHdTcqKUI6CXzfzT1XjmEyRf1J311RQh9zsG0DI8mpeo41U38ggdbPyOF6AQ/fOqngTjtrBf4kxwys2u1lEyNTjqeZGErmTQHn4G6THYG3lGyV9coqTHtiEM+qh3cadIF6h7avdO334294Hi/JFydqo7x919A98jk1s2ECQ29V2i3wfoTjPPH78whHGSQwsgSYaqPziGiaK6ab0KCu3NEKwjG8GxWKBSxgsSKKvqw==
    user: AgAupvsFhpmKvsYb3LJ7gzM0ZGcMHAvgJDsYYmI4lqwEPg/NxCA0CktwbRIgQOh8SqPH4psLQupyvNLdapIbDJYvf+fldEsFcEUTRwOer0NZjpUnmDoeAtPTkWZWfI6d7r4ZfzRpOeoyFyRFZvPP2NRzccHolzjJoTpAs9OpG+X79iPeJNiH2mHk5fygNrKg8I/iKAOMquJsDFoTqXaXyrgYmMc9kp1ay5V24H3PxO5QDDV2X9E/fkSfCnRf3wOfnGijr4kCNURWQ3ZE2j9ob2HePz0jKuzMlacl5j46mlWUneXcGmvz6RP8buakreuBBbwIfqFE9jL9/uiLm8X5WjTNdL2gY0nrdpafbMA2C0l3DIz9coPjGVGBqeO+5EhA3vZSztGWZNaBi+LRoonhI/D1KhtdmDK80iam8Jzmig1rNaY4r6u3DnPpmGFGmcTJcroqovlt4YIORSd/59n+5juq4d3U4afeVCRxoJigEDDt9uIPnS6QXouuyqI2RY3BTDFGPDcyBNL8MtJuHxMlN8vLFZYUf1OYnjm6kGvRRD148r0piLZYSBvamzPftWlgvMr16ctT8A5T805Wk7IKKM6pe638ubpbL3BA0I6YyUYLYdTcwSrjf4/NPTCebEA2zp/dIDHBLeCugDEe7/k9xKzPqAEWfAESSDt+L7hWfBcvTXXAHDW0b4TMlUGxNQxw6+6hqr9h2Q==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: helm-harbor
      namespace: monitoring

