apiVersion: v2
description: A Helm chart for masgustavos/alertmanager-discord
home: https://github.com/masgustavos/helm/tree/main/charts/alertmanager-discord
keywords:
- alertmanager
- discord
- prometheus
- kubernetes
- webhook
maintainers:
- email: gustavosteinmattos@gmail.com
  name: Gustavo Stein
  url: https://github.com/masgustavos
name: alertmanager-discord
type: application
version: 0.0.5
