apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 1h
  chart:
    spec:
      chart: external-dns
      version: '6.x.x'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: external-dns
      interval: 1h
  values:
    provider: rfc2136
    rfc2136:
      host: 192.168.40.250
      secretName: tsig-secret
      tsigSecretAlg: HMACSHA512
      tsigKeyName: letsencrypt
