apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: tsig-secret
  namespace: external-dns
spec:
  encryptedData:
    rfc2136_tsig_secret: AgB3i3lJLsJXdbh3Y5S6gPoBSnPh6z3mnRbZywyqGFsGohd7UnOLc3gdfOKuJlTt8t/xk69TUZ0no+15lFaq3sRntD0AfML/VDcn6jzBT2xihyWRq9kllxS+dibJFabN9aUSVWDlQ2qQPH9G1OOkWnV4FhyjLgy4QCM8/uvg7HG77pHCThvMLSC69ysXDuOmCkl0+KfouzJImnCmDhUB7ed7x2oeVfKRQ9vNdVQj4QLtA8uFTxvUP/Svo5hnSjUUqcWRHnQBq5Vs6Gt6+hzhvkFpUigu5R9w7945ouVY/+fLa8C4kA6gJf6BU7FPmqT9RAtyK/CNcekukyPQd7KVc+mcgwHMVIsMwsHyelD/TWr+uDxr70rQjUiOkQNeh+a1AfMOFOSJGrGqvWlTo25AZ2i57RrKt2+BKB23haGtWjOX25qZWwyJIb1Ypu0HhXCF+GalEfQDdeEmmuhPUeZRdeb9lUbHEBiqNMtX9Zrr2zYSrnbn9maDzMcrN28x1jsBkngj4zO8qAsh+rRQox/l/kYj8KjOuWkKS2uR01laWLqdeQx++zzeSnjknWwYokV7uN3WOdLpYDkZkTeB5jXL4zIjWF66V2BbKnpXqGEMU5aPhsDdizJ09D3JBVYr36C4z8kyod0RMaSCLf6aHLdAB29j7Fq5EaKNkevwPsvGPfmM+M7IPbDA1pUsiFYbYxCdDs6FQNCeyFN0CQPUamC/kYm4yZZK2aADp8ozdLveu3nKEuORgp9o+W4Jkgw9bgvtkIiqU/UI8zktQG/84tFD2PIKjb/tSB8QBWwYDaUI+lqIR/1eoUp0lehM
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: tsig-secret
      namespace: external-dns

