kind: Certificate
apiVersion: cert-manager.io/v1
metadata:
  name: mosquitto
  namespace: domotique
spec:
  dnsNames:
    - mosquitto.iot.cohenc.fr
    - mqtt.iot.cohenc.fr
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: mosquitto-tls
