---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: domotique
spec:
  chart:
    spec:
      chart: mosquitto
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: t3n
      version: 2.4.1
  interval: 1h
  values:
    service:
      type: LoadBalancer
      loadBalancerIP: 192.168.40.200
      annotations:
        external-dns.alpha.kubernetes.io/hostname: mqtt.iot.cohenc.fr
        external-dns.alpha.kubernetes.io/ttl: "60"
    monitoring:
      ports:
        mqtt:
          port: 8883
      extraVolumes:
        - name: tls
          secret:
            secretName: mosquitto-tls
      extraVolumeMounts:
        - name: tls
          mountPath: /certs
      podMonitor:
        enabled: true
      sidecar:
        enabled: true
      config: |
        persistence true
        persistence_location /mosquitto/data/
        log_dest stdout
        listener 8883
        listener 9090
        protocol websockets
        require_cert true
        certfile /certs/tls.crt
        keyfile /certs/tls.key
    

