---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: domotique
spec:
  chart:
    spec:
      chart: mosquitto
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: t3n
      version: 2.4.1
  interval: 1h
  values:
    service:
      type: LoadBalancer
      loadBalancerIP: 192.168.40.200
      annotations:
        external-dns.alpha.kubernetes.io/hostname: mqtt.iot.cohenc.fr
        external-dns.alpha.kubernetes.io/ttl: "60"
    ports:
      mqtt:
        port: 1883
      mqtts:
        port: 8883
    extraVolumes:
      - name: tls
        secret:
          secretName: mosquitto-tls
    extraVolumeMounts:
      - name: tls
        mountPath: /certs
    existingConfigMap: mosquitto-conf

    monitoring:
      podMonitor:
        enabled: false
      sidecar:
        enabled: false

        
    

