apiVersion: v1
kind: ConfigMap
metadata:
  name: user-workload-monitoring-config
  namespace: openshift-user-workload-monitoring
data:
  config.yaml: |
    prometheus: 
      retention: 1y
      volumeClaimTemplate:
        spec:
          storageClassName: thin
          resources:
            requests:
              storage: 40Gi
      resources:
        requests:
          cpu: 200m 
          memory: 2Gi 